---
title: "eds212-day4-comp1"
author: "Anna Ramji"
date: "2023-08-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rain <- c(1, 2, 4.1, 29)
# check the class / type of your vector etc. by: "class(vector)" in console

 

```

making a change for practice :)

```{r}
my_values <- seq(from = 1, to = 10)


```

```{r}
# wrapping this into a 2 x 5 matrix

# populated w values by column is default (byrow = FALSE)

# populate w values by row, matrix(.... , byrow = TRUE)

my_matrix <- matrix(data = my_values, nrow = 2, ncol = 5, byrow = TRUE)


```

```{r}
# this will return a warning that lets you know that your data length is [10], which doesn't fit cleanly into your 3x4 matrix (need 12 values)

my_matrix2 <- matrix(data = my_values, nrow = 3, ncol = 4, byrow = TRUE)

# if we run my_matrix_2, it will fill in the missing values by repeating your values (1, 2, ...)
```

```{r}
matrixA <- matrix(data = seq(from = 2, to = 5, length = 10),
                  nrow = 2, 
                  ncol = 5, 
                  byrow = TRUE)
```
